# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mazijie/CLionProjects/tiny_db

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mazijie/CLionProjects/tiny_db

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mazijie/CLionProjects/tiny_db/CMakeFiles /Users/mazijie/CLionProjects/tiny_db/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mazijie/CLionProjects/tiny_db/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tiny_db

# Build rule for target.
tiny_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tiny_db
.PHONY : tiny_db

# fast build rule for target.
tiny_db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/build
.PHONY : tiny_db/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/main.cpp.s
.PHONY : main.cpp.s

src/part_command/Command.o: src/part_command/Command.cpp.o

.PHONY : src/part_command/Command.o

# target to build an object file
src/part_command/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_command/Command.cpp.o
.PHONY : src/part_command/Command.cpp.o

src/part_command/Command.i: src/part_command/Command.cpp.i

.PHONY : src/part_command/Command.i

# target to preprocess a source file
src/part_command/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_command/Command.cpp.i
.PHONY : src/part_command/Command.cpp.i

src/part_command/Command.s: src/part_command/Command.cpp.s

.PHONY : src/part_command/Command.s

# target to generate assembly for a file
src/part_command/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_command/Command.cpp.s
.PHONY : src/part_command/Command.cpp.s

src/part_cursor/Cursor.o: src/part_cursor/Cursor.cpp.o

.PHONY : src/part_cursor/Cursor.o

# target to build an object file
src/part_cursor/Cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_cursor/Cursor.cpp.o
.PHONY : src/part_cursor/Cursor.cpp.o

src/part_cursor/Cursor.i: src/part_cursor/Cursor.cpp.i

.PHONY : src/part_cursor/Cursor.i

# target to preprocess a source file
src/part_cursor/Cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_cursor/Cursor.cpp.i
.PHONY : src/part_cursor/Cursor.cpp.i

src/part_cursor/Cursor.s: src/part_cursor/Cursor.cpp.s

.PHONY : src/part_cursor/Cursor.s

# target to generate assembly for a file
src/part_cursor/Cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_cursor/Cursor.cpp.s
.PHONY : src/part_cursor/Cursor.cpp.s

src/part_input/InputBuffer.o: src/part_input/InputBuffer.cpp.o

.PHONY : src/part_input/InputBuffer.o

# target to build an object file
src/part_input/InputBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_input/InputBuffer.cpp.o
.PHONY : src/part_input/InputBuffer.cpp.o

src/part_input/InputBuffer.i: src/part_input/InputBuffer.cpp.i

.PHONY : src/part_input/InputBuffer.i

# target to preprocess a source file
src/part_input/InputBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_input/InputBuffer.cpp.i
.PHONY : src/part_input/InputBuffer.cpp.i

src/part_input/InputBuffer.s: src/part_input/InputBuffer.cpp.s

.PHONY : src/part_input/InputBuffer.s

# target to generate assembly for a file
src/part_input/InputBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_input/InputBuffer.cpp.s
.PHONY : src/part_input/InputBuffer.cpp.s

src/part_process/Process.o: src/part_process/Process.cpp.o

.PHONY : src/part_process/Process.o

# target to build an object file
src/part_process/Process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_process/Process.cpp.o
.PHONY : src/part_process/Process.cpp.o

src/part_process/Process.i: src/part_process/Process.cpp.i

.PHONY : src/part_process/Process.i

# target to preprocess a source file
src/part_process/Process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_process/Process.cpp.i
.PHONY : src/part_process/Process.cpp.i

src/part_process/Process.s: src/part_process/Process.cpp.s

.PHONY : src/part_process/Process.s

# target to generate assembly for a file
src/part_process/Process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_process/Process.cpp.s
.PHONY : src/part_process/Process.cpp.s

src/part_table/Pager.o: src/part_table/Pager.cpp.o

.PHONY : src/part_table/Pager.o

# target to build an object file
src/part_table/Pager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Pager.cpp.o
.PHONY : src/part_table/Pager.cpp.o

src/part_table/Pager.i: src/part_table/Pager.cpp.i

.PHONY : src/part_table/Pager.i

# target to preprocess a source file
src/part_table/Pager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Pager.cpp.i
.PHONY : src/part_table/Pager.cpp.i

src/part_table/Pager.s: src/part_table/Pager.cpp.s

.PHONY : src/part_table/Pager.s

# target to generate assembly for a file
src/part_table/Pager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Pager.cpp.s
.PHONY : src/part_table/Pager.cpp.s

src/part_table/Row.o: src/part_table/Row.cpp.o

.PHONY : src/part_table/Row.o

# target to build an object file
src/part_table/Row.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Row.cpp.o
.PHONY : src/part_table/Row.cpp.o

src/part_table/Row.i: src/part_table/Row.cpp.i

.PHONY : src/part_table/Row.i

# target to preprocess a source file
src/part_table/Row.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Row.cpp.i
.PHONY : src/part_table/Row.cpp.i

src/part_table/Row.s: src/part_table/Row.cpp.s

.PHONY : src/part_table/Row.s

# target to generate assembly for a file
src/part_table/Row.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Row.cpp.s
.PHONY : src/part_table/Row.cpp.s

src/part_table/Table.o: src/part_table/Table.cpp.o

.PHONY : src/part_table/Table.o

# target to build an object file
src/part_table/Table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Table.cpp.o
.PHONY : src/part_table/Table.cpp.o

src/part_table/Table.i: src/part_table/Table.cpp.i

.PHONY : src/part_table/Table.i

# target to preprocess a source file
src/part_table/Table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Table.cpp.i
.PHONY : src/part_table/Table.cpp.i

src/part_table/Table.s: src/part_table/Table.cpp.s

.PHONY : src/part_table/Table.s

# target to generate assembly for a file
src/part_table/Table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_table/Table.cpp.s
.PHONY : src/part_table/Table.cpp.s

src/part_tree/Node.o: src/part_tree/Node.cpp.o

.PHONY : src/part_tree/Node.o

# target to build an object file
src/part_tree/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_tree/Node.cpp.o
.PHONY : src/part_tree/Node.cpp.o

src/part_tree/Node.i: src/part_tree/Node.cpp.i

.PHONY : src/part_tree/Node.i

# target to preprocess a source file
src/part_tree/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_tree/Node.cpp.i
.PHONY : src/part_tree/Node.cpp.i

src/part_tree/Node.s: src/part_tree/Node.cpp.s

.PHONY : src/part_tree/Node.s

# target to generate assembly for a file
src/part_tree/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tiny_db.dir/build.make CMakeFiles/tiny_db.dir/src/part_tree/Node.cpp.s
.PHONY : src/part_tree/Node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tiny_db"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/part_command/Command.o"
	@echo "... src/part_command/Command.i"
	@echo "... src/part_command/Command.s"
	@echo "... src/part_cursor/Cursor.o"
	@echo "... src/part_cursor/Cursor.i"
	@echo "... src/part_cursor/Cursor.s"
	@echo "... src/part_input/InputBuffer.o"
	@echo "... src/part_input/InputBuffer.i"
	@echo "... src/part_input/InputBuffer.s"
	@echo "... src/part_process/Process.o"
	@echo "... src/part_process/Process.i"
	@echo "... src/part_process/Process.s"
	@echo "... src/part_table/Pager.o"
	@echo "... src/part_table/Pager.i"
	@echo "... src/part_table/Pager.s"
	@echo "... src/part_table/Row.o"
	@echo "... src/part_table/Row.i"
	@echo "... src/part_table/Row.s"
	@echo "... src/part_table/Table.o"
	@echo "... src/part_table/Table.i"
	@echo "... src/part_table/Table.s"
	@echo "... src/part_tree/Node.o"
	@echo "... src/part_tree/Node.i"
	@echo "... src/part_tree/Node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

